import PoliticalFactCheckScripting

// UI can use the neutral contract through its existing AppModel package product.
public typealias ScriptGenerationInput = PoliticalFactCheckScripting.ScriptGenerationInput
public typealias ScriptGenerationOutput = PoliticalFactCheckScripting.ScriptGenerationOutput
public typealias GeneratedScriptStatement = PoliticalFactCheckScripting.GeneratedScriptStatement
public typealias OpenAITransmissionPreview = PoliticalFactCheckScripting.OpenAITransmissionPreview
public typealias OpenAIScriptProviderConfiguration = PoliticalFactCheckScripting.OpenAIScriptProviderConfiguration
public typealias ScriptReviewPlan = PoliticalFactCheckScripting.ScriptReviewPlan
public typealias ScriptReviewItem = PoliticalFactCheckScripting.ScriptReviewItem
public typealias ScriptReviewSourceSummary = PoliticalFactCheckScripting.ScriptReviewSourceSummary

import PoliticalFactCheckVideoPlanning
public typealias VideoScriptHandoffV1 = PoliticalFactCheckVideoPlanning.VideoScriptHandoffV1
public typealias VideoSceneV1 = PoliticalFactCheckVideoPlanning.VideoSceneV1

import PoliticalFactCheckExport
public typealias EditorialPackageSummary = PoliticalFactCheckExport.EditorialPackageSummary
